<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestaurantMenuSeeder extends Seeder
{
    public function run(): void
    {
        // Önce kategorileri ekle
        DB::table('urunlerkategori')->insert([
            [
                'id' => 1,
                'restaurant_id' => 2,
                'kategori_adi' => 'Ana Yemekler',
                'aciklama' => 'Lezzetli ana yemek çeşitlerimiz',
                'KDV' => 20.00,
                'resim' => '🍖',
                'sira' => 1,
                'aktif' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'restaurant_id' => 2,
                'kategori_adi' => 'Başlangıçlar',
                'aciklama' => 'Nefis meze ve başlangıç çeşitleri',
                'KDV' => 20.00,
                'resim' => '🥗',
                'sira' => 2,
                'aktif' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'restaurant_id' => 2,
                'kategori_adi' => 'İçecekler',
                'aciklama' => 'Soğuk ve sıcak içecekler',
                'KDV' => 8.00,
                'resim' => '🥤',
                'sira' => 3,
                'aktif' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'restaurant_id' => 2,
                'kategori_adi' => 'Tatlılar',
                'aciklama' => 'Ev yapımı tatlı çeşitlerimiz',
                'KDV' => 20.00,
                'resim' => '🍰',
                'sira' => 4,
                'aktif' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Sonra ürünleri ekle
        DB::table('urunler')->insert([
            // Ana Yemekler (kategori_id: 1)
            [
                'restaurant_id' => 2,
                'kategori_id' => 1,
                'urunadi' => 'Adana Kebap',
                'aciklama' => 'Özel baharatlarla hazırlanmış acılı köfte',
                'fiyat' => 85.00,
                'resim' => '🍖',
                'hazirlanma_suresi' => 15,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'kategori_id' => 1,
                'urunadi' => 'Urfa Kebap',
                'aciklama' => 'Acısız, lezzetli köfte çeşidi',
                'fiyat' => 80.00,
                'resim' => '🍖',
                'hazirlanma_suresi' => 15,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'kategori_id' => 1,
                'urunadi' => 'Tavuk Şiş',
                'aciklama' => 'Marine edilmiş tavuk göğsü',
                'fiyat' => 75.00,
                'resim' => '🍗',
                'hazirlanma_suresi' => 12,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'kategori_id' => 1,
                'urunadi' => 'Kuzu Pirzola',
                'aciklama' => 'Izgara kuzu pirzola, sebze garnitür',
                'fiyat' => 120.00,
                'resim' => '🥩',
                'hazirlanma_suresi' => 18,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Başlangıçlar (kategori_id: 2)
            [
                'restaurant_id' => 2,
                'kategori_id' => 2,
                'urunadi' => 'Humus',
                'aciklama' => 'Nohut ezmesi, tahin ve zeytinyağı',
                'fiyat' => 25.00,
                'resim' => '🧄',
                'hazirlanma_suresi' => 5,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'kategori_id' => 2,
                'urunadi' => 'Közlenmiş Patlıcan Salatası',
                'aciklama' => 'Közde pişmiş patlıcan, domates, biber',
                'fiyat' => 30.00,
                'resim' => '🍆',
                'hazirlanma_suresi' => 8,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'kategori_id' => 2,
                'urunadi' => 'Çoban Salatası',
                'aciklama' => 'Domates, salatalık, soğan, maydanoz',
                'fiyat' => 20.00,
                'resim' => '🥗',
                'hazirlanma_suresi' => 5,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // İçecekler (kategori_id: 3)
            [
                'restaurant_id' => 2,
                'kategori_id' => 3,
                'urunadi' => 'Çay',
                'aciklama' => 'Geleneksel Türk çayı',
                'fiyat' => 8.00,
                'resim' => '☕',
                'hazirlanma_suresi' => 3,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'kategori_id' => 3,
                'urunadi' => 'Ayran',
                'aciklama' => 'Ev yapımı tuzlu ayran',
                'fiyat' => 12.00,
                'resim' => '🥛',
                'hazirlanma_suresi' => 2,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'kategori_id' => 3,
                'urunadi' => 'Kola',
                'aciklama' => 'Soğuk kola 330ml',
                'fiyat' => 15.00,
                'resim' => '🥤',
                'hazirlanma_suresi' => 1,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'kategori_id' => 3,
                'urunadi' => 'Türk Kahvesi',
                'aciklama' => 'Geleneksel Türk kahvesi',
                'fiyat' => 18.00,
                'resim' => '☕',
                'hazirlanma_suresi' => 8,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tatlılar (kategori_id: 4)
            [
                'restaurant_id' => 2,
                'kategori_id' => 4,
                'urunadi' => 'Baklava',
                'aciklama' => 'Fıstıklı geleneksel baklava',
                'fiyat' => 45.00,
                'resim' => '🥧',
                'hazirlanma_suresi' => 5,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'kategori_id' => 4,
                'urunadi' => 'Künefe',
                'aciklama' => 'Sıcak künefe, dondurma ile servis',
                'fiyat' => 50.00,
                'resim' => '🧁',
                'hazirlanma_suresi' => 8,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'kategori_id' => 4,
                'urunadi' => 'Sütlaç',
                'aciklama' => 'Ev yapımı fırın sütlaç',
                'fiyat' => 25.00,
                'resim' => '🍮',
                'hazirlanma_suresi' => 3,
                'stokta_var' => 1,
                'aktif' => 1,
                'sira' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}